#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
name: 'Contactually'
version: '0.0.0.1'

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
analysis-paths: ["analysis"]
data-paths: ["data"]

model-defaults:
  materialized: view
  enabled: true

models:
  Contactually:
    post-hook: "grant select on table {{this}} to looker"
    base:
      events:
        materialized: table
        sort: [domain_userid, domain_sessionidx]
        dist: domain_userid
    finance:
      materialized: table
    transform:
      normal_channel_mapping:
        materialized: table
      sessions:
        materialized: table
      sessions_joined:
        materialized: view
      enriched_events:
        materialized: table
      sessions_enriched:
        materialized: table
        sort: [session_id, session_start_tstamp]
        dist: session_id
      multitouch:
        enabled: false
      multitouch_timeseries:
        materialized: table
    ads:
      base:
        ad_performance_all:
          materialized: table
      transform:
        materialized: table

  Snowplow:
    post-hook: "grant select on table {{this}} to looker"
    vars:
      events_table: "{{ ref('enriched_events') }}"
      country_codes_table: 'dbt_dbanin.country_codes'

  quickbooks:
    post-hook: "grant select on table {{this}} to looker"
    materialized: ephemeral
    tables:
      materialized: table
      quickbooks_parent_class_map:
        enabled: true
    base:
      quickbooks_classes:
        materialized: table
        enabled: true
    transform:
      quickbooks_toplevel_account_metrics:
        materialized: table

    vars:
      "base.accounts"                     : "quickbooks.quickbooks_accounts"
      "base.bills_line"                   : "quickbooks.quickbooks_bills__line"
      "base.billpayments"                 : "quickbooks.quickbooks_billpayments"
      "base.billpayments_line"            : "quickbooks.quickbooks_billpayments__line"
      "base.billpayments_line__linkedtxn" : "quickbooks.quickbooks_billpayments__line__linkedtxn"
      "base.bills"                        : "quickbooks.quickbooks_bills"
      "base.classes"                      : "quickbooks.quickbooks_classes"
      "base.customers"                    : "quickbooks.quickbooks_customers"
      "base.deposits_line"                : "quickbooks.quickbooks_deposits__line"
      "base.deposits_line_linkedtxn"      : "quickbooks.quickbooks_deposits__line__linkedtxn"
      "base.deposits"                     : "quickbooks.quickbooks_deposits"
      "base.invoices_lines"               : "quickbooks.quickbooks_invoices__line"
      "base.invoices"                     : "quickbooks.quickbooks_invoices"
      "base.items"                        : "quickbooks.quickbooks_items"
      "base.journal_entries"              : "quickbooks.quickbooks_journalentries"
      "base.journal_entries_line"         : "quickbooks.quickbooks_journalentries__line"
      "base.payments"                     : "quickbooks.quickbooks_payments"
      "base.purchases_line"               : "quickbooks.quickbooks_purchases__line"
      "base.purchases"                    : "quickbooks.quickbooks_purchases"
      "base.vendors"                      : "quickbooks.quickbooks_vendors"
      "level_0_id_field"                  : "_sdc_level_0_id"
      "source_key_id_field"               : "_sdc_source_key_id"
      "uses_classes"                       : "true"


profile: "contactually"

repositories:
  - "git@github.com:fishtown-analytics/snowplow.git@with-referer"
  - "https://github.com/analyst-collective/dbt-audit.git"
  - "git@github.com:fishtown-analytics/quickbooks.git@with-types"
