#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
name: 'Contactually'
version: '0.0.0.1'

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
data-paths: ["data"]

models:
  post-hook: "grant select on table {{this}} to looker"
  Contactually:
    finance:
      tables:
        finance_cogs:
          materialized: table
          sort: txn_date
          dist: txn_date
        finance_marketing_costs:
          materialized: table
          sort: txn_date
          dist: txn_date

  quickbooks:
    post-hook: "grant select on table {{this}} to looker"
    materialized: ephemeral
    tables:
      materialized: table
      quickbooks_parent_class_map:
    base:
      quickbooks_classes:
        materialized: table
    transform:
      quickbooks_toplevel_account_metrics:
        materialized: table
      quickbooks_toplevel_class_metrics:
        materialized: table

    vars:
      "base.accounts"                     : '{{ ref("quickbooks_accounts_fivetran") }}'
      "base.bills_line"                   : '{{ ref("quickbooks_bill_lines_fivetran") }}'
      "base.billpayments"                 : '{{ ref("quickbooks_bill_payments_fivetran") }}'
      "base.billpayments_line"            : '{{ ref("quickbooks_bill_payments_line_fivetran") }}'
      "base.billpayments_line__linkedtxn" : '{{ ref("quickbooks_bill_payments_line_transaction_fivetran") }}'
      "base.bills"                        : '{{ ref("quickbooks_bills_fivetran") }}'
      "base.classes"                      : '{{ ref("quickbooks_classes_fivetran") }}'
      "base.customers"                    : '{{ ref("quickbooks_customers_fivetran") }}'
      "base.deposits_line"                : '{{ ref("quickbooks_deposit_lines_fivetran") }}'
      "base.deposits_line_linkedtxn"      : '{{ ref("quickbooks_deposit_line_transactions_fivetran") }}'
      "base.deposits"                     : '{{ ref("quickbooks_deposits_fivetran") }}'
      "base.invoices_lines"               : '{{ ref("quickbooks_invoice_lines_fivetran") }}'
      "base.invoices"                     : '{{ ref("quickbooks_invoices_fivetran") }}'
      "base.items"                        : '{{ ref("quickbooks_items_fivetran") }}'
      "base.journal_entries"              : '{{ ref("quickbooks_journal_entries_fivetran") }}'
      "base.journal_entries_line"         : '{{ ref("quickbooks_journal_entry_lines_fivetran") }}'
      "base.payments"                     : '{{ ref("quickbooks_payments_fivetran") }}'
      "base.purchases_line"               : '{{ ref("quickbooks_purchase_lines_fivetran") }}'
      "base.purchases"                    : '{{ ref("quickbooks_purchases_fivetran") }}'
      "base.vendors"                      : '{{ ref("quickbooks_vendors_fivetran") }}'
      "level_0_id_field"                  : "level_id"
      "source_key_id_field"               : "source_key"

profile: "contactually"

repositories:
  - "https://github.com/fishtown-analytics/quickbooks.git@v0.1.0"
