#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
name: 'Contactually'
version: '0.0.0.1'

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
data-paths: ["data"]

models:
  post-hook: "grant select on table {{this}} to looker"
  Contactually:
    app:
      base:
        materialized: ephemeral
    ads:
      base:
        materialized: ephemeral

    salesforce:
      base:
        materialized: ephemeral

    snowplow:
      base:
        materialized: ephemeral
        base_events:
          materialized: view

    finance:
      tables:
        materialized: table
        sort: txn_date
        dist: txn_date

  Snowplow:
    post-hook: "grant select on table {{this}} to looker"
    vars:
      events_table: "{{ ref('base_events') }}"
      country_codes_table: '{{ this.schema }}.country_codes'

  quickbooks:
    post-hook: "grant select on table {{this}} to looker"
    materialized: ephemeral
    tables:
      materialized: table
      quickbooks_parent_class_map:
        enabled: true
    base:
      quickbooks_classes:
        materialized: table
        enabled: true
    transform:
      quickbooks_toplevel_account_metrics:
        materialized: table
      quickbooks_toplevel_class_metrics:
        materialized: table
 
    vars:
      "base.accounts"                     : "quickbooks.quickbooks_accounts"
      "base.bills_line"                   : "quickbooks.quickbooks_bills__line"
      "base.billpayments"                 : "quickbooks.quickbooks_billpayments"
      "base.billpayments_line"            : "quickbooks.quickbooks_billpayments__line"
      "base.billpayments_line__linkedtxn" : "quickbooks.quickbooks_billpayments__line__linkedtxn"
      "base.bills"                        : "quickbooks.quickbooks_bills"
      "base.classes"                      : "quickbooks.quickbooks_classes"
      "base.customers"                    : "quickbooks.quickbooks_customers"
      "base.deposits_line"                : "quickbooks.quickbooks_deposits__line"
      "base.deposits_line_linkedtxn"      : "quickbooks.quickbooks_deposits__line__linkedtxn"
      "base.deposits"                     : "quickbooks.quickbooks_deposits"
      "base.invoices_lines"               : "quickbooks.quickbooks_invoices__line"
      "base.invoices"                     : "quickbooks.quickbooks_invoices"
      "base.items"                        : "quickbooks.quickbooks_items"
      "base.journal_entries"              : "quickbooks.quickbooks_journalentries"
      "base.journal_entries_line"         : "quickbooks.quickbooks_journalentries__line"
      "base.payments"                     : "quickbooks.quickbooks_payments"
      "base.purchases_line"               : "quickbooks.quickbooks_purchases__line"
      "base.purchases"                    : "quickbooks.quickbooks_purchases"
      "base.vendors"                      : "quickbooks.quickbooks_vendors"
      "level_0_id_field"                  : "_sdc_level_0_id"
      "source_key_id_field"               : "_sdc_source_key_id"
      "uses_classes"                       : "true"
 
  facebook_ads:
    materialized: ephemeral
    stitch:
      transform:
        fb_ad_insights_xf:
          materialized: view
    vars:
      ad_creatives_table                  : 'facebook_contactually_ads.facebook_adcreative_26288427'
      ads_insights_table                  : 'facebook_contactually_ads.facebook_ads_insights_26288427'
      ads_table                           : 'facebook_contactually_ads.facebook_ads_26288427'
      ads_insights_agegender_table        : 'facebook_contactually_ads.facebook_ads_insights_age_and_gender_26288427'
      ads_insights_country_table          : 'facebook_contactually_ads.facebook_ads_insights_country_26288427'
      ads_insights_placement_device_table : 'facebook_contactually_ads.facebook_ads_insights_placement_and_device_26288427'
      campaigns_table                     : 'facebook_contactually_ads.facebook_campaigns_26288427'


profile: "contactually"

repositories:
  - "https://github.com/fishtown-analytics/snowplow.git@0.2.0"
  - "https://github.com/fishtown-analytics/quickbooks.git@v0.1.0"
  - "https://github.com/fishtown-analytics/facebook-ads@v0.1.6"
