#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
name: 'Contactually'
version: '0.0.0.1'

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
analysis-paths: ["analysis"]
data-paths: ["data"]

model-defaults:
  materialized: view
  enabled: true

models:
  Contactually:
    base:
      events:
        materialized: table
        sort: [domain_userid, domain_sessionidx]
        dist: domain_userid
    transform:
      normal_channel_mapping:
        materialized: table
      sessions:
        materialized: table
      sessions_joined:
        materialized: view
      sessions_enriched:
        materialized: table
        sort: [session_id, session_start_tstamp]
        dist: session_id
      multitouch:
        enabled: false
      multitouch_timeseries:
        materialized: table

profile: "contactually"

repositories:
  - "git@github.com:fishtown-analytics/snowplow.git"
