#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
name: 'Contactually'
version: '0.0.0.1'

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
analysis-paths: ["analysis"]
data-paths: ["data"]

model-defaults:
  materialized: false
  enabled: true

profile: "contactually"

repositories:
  - "git@github.com:fishtown-analytics/snowplow.git"
