

visitors:
    constraints:
        not_null:
            - blended_user_id
            - first_touch_tstamp
            - last_touch_tstamp
        unique:
            - blended_user_id

sessions_with_channels:
    constraints:
        not_null:
            - blended_user_id
            - session_id
            - blended_sessionidx
            - domain_userid

        unique:
            - blended_user_id || '-' || blended_sessionidx
            - domain_userid || '-' || domain_sessionidx
            - session_id

        relationships:
            - { from: blended_user_id, to: visitors, field: blended_user_id }

sessions_with_attribution:
    constraints:
        not_null:
            - blended_user_id
            - session_id
            - blended_sessionidx
            - domain_userid

        unique:
            - blended_user_id || '-' || blended_sessionidx
            - domain_userid || '-' || domain_sessionidx
            - session_id

        relationships:
            - { from: blended_user_id, to: visitors, field: blended_user_id }

        accepted_values:
            - { field: "(attribution_points <= 1.00)", values: [true] }


