

sp_visitors:
    constraints:
        not_null:
            - blended_user_id
            - first_touch_tstamp
            - last_touch_tstamp
        unique:
            - blended_user_id

sp_sessions_with_channels:
    constraints:
        not_null:
            - blended_user_id
            - session_id
            - blended_sessionidx
            - domain_userid

        unique:
            - blended_user_id || '-' || blended_sessionidx
            - domain_userid || '-' || domain_sessionidx
            - session_id

        relationships:
            - { from: blended_user_id, to: sp_visitors, field: blended_user_id }

sp_sessions_with_attribution:
    constraints:
        not_null:
            - blended_user_id
            - session_id
            - blended_sessionidx
            - domain_userid

            # make sure every session gets between 0 and 1 points
            - case when attribution_points <= 1.00 then true else null end

            # make sure utm campaign passes through to mapped campaign
            - case when mapped_campaign is null and mkt_campaign is not null then null else true end

            # make sure utm source passes through to mapped source
            - case when mapped_source is null and mkt_source is not null then null else true end

        unique:
            - blended_user_id || '-' || blended_sessionidx
            - domain_userid || '-' || domain_sessionidx
            - session_id

        relationships:
            - { from: blended_user_id, to: sp_visitors, field: blended_user_id }


